name: "Poosh"
description: "Attempts to push changes directly to the specified branch. If direct push is not possible (e.g., due to permissions or branch protection), creates a new branch and opens a pull request to the target branch instead."
icon: package
color: blue
inputs:
  commit-message:
    description: "Commit message to use when committing changes."
    required: true
  trigger-branch:
    description: "The branch where changes were made and where the action will attempt to push directly. If direct push fails, a PR will be opened to this branch."
    required: true
  pr-branch:
    description: "The name of the branch to create and push from if a PR is needed. If not provided, defaults to 'poosh/{trigger-branch}'. If provided and does not contain '/', it will be prefixed with 'poosh/'."
    required: false
    default: ""
  pr-base:
    description: "The base branch to target if a PR is needed. Defaults to the trigger-branch."
    required: false
    default: ""
  trigger-pr-number:
    description: "Optional: PR number of the triggering PR (e.g., 1234). If set, the PR body will include 'Triggered by #<number>'."
    required: false
    default: ""
  pr-body:
    description: "The body content for the pull request. If not provided, a default message will be used, followed by trigger info."
    required: false
    default: "This PR was generated by [Poosh](https://github.com/BobTheBuidler/poosh) as part of a GitHub Actions workflow"
outputs:
  trigger-branch:
    description: "The branch that was pushed to or targeted by the PR."
  commit-sha:
    description: "The commit SHA of the pushed commit (if a commit was made)."
  pr-url:
    description: "The URL of the created pull request (if a PR was opened)."
  pr-number:
    description: "The number of the created pull request (if a PR was opened)."
runs:
  using: "composite"
  steps:
    - name: Validate 'commit-message'
      run: |
        if [[ -z "${{ inputs.commit-message }}" || -z "$(echo "${{ inputs.commit-message }}" | xargs)" ]]; then
          echo "ERROR: 'commit-message' is required and must be a non-empty string."
          exit 1
        fi
      shell: bash

    - name: Validate 'trigger-branch'
      run: |
        if [[ -z "${{ inputs.trigger-branch }}" || -z "$(echo "${{ inputs.trigger-branch }}" | xargs)" ]]; then
          echo "ERROR: 'trigger-branch' is required and must be a non-empty string."
          exit 1
        fi
        if [[ "${{ inputs.trigger-branch }}" == *[!a-zA-Z0-9._/-]* ]]; then
          echo "ERROR: 'trigger-branch' contains invalid characters. Only alphanumeric, '.', '_', '-', and '/' are allowed."
          exit 1
        fi
      shell: bash

    - name: Validate 'pr-branch'
      run: |
        if [[ -n "${{ inputs.pr-branch }}" && "${{ inputs.pr-branch }}" == *[!a-zA-Z0-9._/-]* ]]; then
          echo "ERROR: 'pr-branch' contains invalid characters. Only alphanumeric, '.', '_', '-', and '/' are allowed."
          exit 1
        fi
      shell: bash

    - name: Validate 'pr-base'
      run: |
        if [[ -n "${{ inputs.pr-base }}" && "${{ inputs.pr-base }}" == *[!a-zA-Z0-9._/-]* ]]; then
          echo "ERROR: 'pr-base' contains invalid characters. Only alphanumeric, '.', '_', '-', and '/' are allowed."
          exit 1
        fi
      shell: bash

    - name: Checkout trigger branch before commit
      run: |
        set -e
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        if [[ "$current_branch" == "${{ inputs.trigger-branch }}" ]]; then
          exit 0
        fi

        if git ls-remote --exit-code --heads origin "${{ inputs.trigger-branch }}" >/dev/null 2>&1; then
          git fetch origin "${{ inputs.trigger-branch }}:${{ inputs.trigger-branch }}" || git fetch origin "${{ inputs.trigger-branch }}"
          git checkout "${{ inputs.trigger-branch }}"
          git pull origin "${{ inputs.trigger-branch }}" || true
        else
          echo "::notice::Trigger branch '${{ inputs.trigger-branch }}' not found on origin; staying on current HEAD."
        fi
      shell: bash

    - name: Check for changes
      id: check_changes
      run: |
        # Skip staging work when there are no changes to commit.
        if [[ -z "$(git status --porcelain --untracked-files=all)" ]]; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "workflow_changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        git add .
        staged_files="$(git diff --cached --name-only)"
        if [[ -z "$staged_files" ]]; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "workflow_changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "changed=true" >> $GITHUB_OUTPUT
        if echo "$staged_files" | grep -q '^.github/workflows/'; then
          echo "workflow_changes=true" >> $GITHUB_OUTPUT
        else
          echo "workflow_changes=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true'
      id: commit_changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "${{ inputs.commit-message }}"
      shell: bash

    - name: Detect workflow changes
      if: steps.check_changes.outputs.changed == 'true'
      id: workflow_changes
      run: |
        if git show --name-only --pretty="" HEAD -- .github/workflows | grep -q .; then
          echo "workflow_changes=true" >> $GITHUB_OUTPUT
        else
          echo "workflow_changes=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Try direct push to trigger branch
      if: steps.check_changes.outputs.changed == 'true'
      id: try_push
      run: |
        set -e
        push_err_file="$(mktemp)"
        workflow_error_regex="create or update workflow|workflows? permission|workflows? scope"
        if git push origin "HEAD:${{ inputs.trigger-branch }}" > "$push_err_file" 2>&1; then
          echo "push_success=true" >> $GITHUB_OUTPUT
          echo "workflow_push_denied=false" >> $GITHUB_OUTPUT
        else
          echo "push_success=false" >> $GITHUB_OUTPUT
          if grep -Eiq "$workflow_error_regex" "$push_err_file"; then
            echo "workflow_push_denied=true" >> $GITHUB_OUTPUT
          else
            echo "workflow_push_denied=false" >> $GITHUB_OUTPUT
          fi
          cat "$push_err_file" >&2
        fi
      shell: bash

    - name: Validate triggers
      if: steps.check_changes.outputs.changed == 'true' && steps.try_push.outputs.push_success == 'false'
      run: |
        if [[ -z "${{ inputs.trigger-pr-number }}" && -z "${{ inputs.trigger-branch-name }}" ]]; then
          echo "::warning::Neither 'trigger-pr-number' nor 'trigger-branch-name' was set. PR body will not include a trigger reference."
        fi
      shell: bash

    - name: Create PR branch and push (if direct push failed)
      if: steps.check_changes.outputs.changed == 'true' && steps.try_push.outputs.push_success == 'false'
      id: pr_branch
      run: |
        set -e
        workflow_error_regex="create or update workflow|workflows? permission|workflows? scope"
        resolve_base_sha() {
          local base_sha
          base_sha=$(git rev-parse HEAD~1 2>/dev/null || true)
          if [[ -z "$base_sha" && "$(git rev-parse --is-shallow-repository)" == "true" ]]; then
            echo "::notice::Shallow clone detected; fetching one more commit to strip workflow changes."
            git fetch --deepen=1 origin "${{ inputs.trigger-branch }}" >/dev/null 2>&1 || \
              git fetch --deepen=1 origin >/dev/null 2>&1 || true
            base_sha=$(git rev-parse HEAD~1 2>/dev/null || true)
          fi
          if [[ -z "$base_sha" ]]; then
            echo "::error::Unable to resolve the parent commit to strip workflow changes. Ensure checkout fetch-depth is at least 2."
            exit 1
          fi
          echo "$base_sha"
        }
        strip_workflows_and_commit() {
          echo "::warning::Push blocked because workflow files changed and workflows permission is missing. Creating PR without workflow file updates."
          local orig_sha
          local base_sha
          orig_sha=$(git rev-parse HEAD)
          base_sha=$(resolve_base_sha)
          git checkout -B "$PR_BRANCH" "$base_sha"
          git restore --source "$orig_sha" --staged --worktree .
          git restore --source "$base_sha" --staged --worktree .github/workflows || true
          if git diff --cached --quiet; then
            echo "::notice::Only workflow changes detected; nothing to push."
            echo "pr_branch=" >> $GITHUB_OUTPUT
            exit 0
          fi
          git commit -m "${{ inputs.commit-message }}"
        }
        if [[ -z "${{ inputs.pr-branch }}" ]]; then
          PR_BRANCH="poosh/${{ inputs.trigger-branch }}"
        elif [[ "${{ inputs.pr-branch }}" != */* ]]; then
          PR_BRANCH="poosh/${{ inputs.pr-branch }}"
        else
          PR_BRANCH="${{ inputs.pr-branch }}"
        fi
        if [[ "${{ steps.try_push.outputs.workflow_push_denied }}" == "true" && "${{ steps.workflow_changes.outputs.workflow_changes }}" == "true" ]]; then
          strip_workflows_and_commit
        else
          git checkout -b "$PR_BRANCH"
        fi
        push_err_file="$(mktemp)"
        if git push origin "$PR_BRANCH" > "$push_err_file" 2>&1; then
          echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT
          exit 0
        fi
        if grep -Eiq "$workflow_error_regex" "$push_err_file" && \
          [[ "${{ steps.workflow_changes.outputs.workflow_changes }}" == "true" ]]; then
          strip_workflows_and_commit
          git push origin "$PR_BRANCH"
        else
          cat "$push_err_file" >&2
          exit 1
        fi
        echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT
      shell: bash

    - name: Compose PR body
      if: steps.check_changes.outputs.changed == 'true' && steps.try_push.outputs.push_success == 'false'
      id: compose_pr_body
      run: |
        BODY="${{ inputs.pr-body }}"
        if [[ -n "${{ inputs.trigger-pr-number }}" ]]; then
          # Link to PR: https://github.com/${GITHUB_REPOSITORY}/pull/<number>
          BODY="${BODY}"$'\n\n'"[Triggered by PR #${{ inputs.trigger-pr-number }}](https://github.com/${GITHUB_REPOSITORY}/pull/${{ inputs.trigger-pr-number }})"
        else
          # Link to branch: https://github.com/${GITHUB_REPOSITORY}/tree/<branch>
          BODY="${BODY}"$'\n\n'"[Triggered by recent changes on branch \`${{ inputs.trigger-branch }}\`](https://github.com/${GITHUB_REPOSITORY}/tree/${{ inputs.trigger-branch }})"
        fi
        echo "body<<EOF" >> $GITHUB_OUTPUT
        echo "$BODY" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Pull Request (if direct push failed)
      if: steps.check_changes.outputs.changed == 'true' && steps.try_push.outputs.push_success == 'false' && steps.pr_branch.outputs.pr_branch != ''
      id: create_pr
      uses: peter-evans/create-pull-request@v8
      with:
        branch: ${{ steps.pr_branch.outputs.pr_branch }}
        base: ${{ inputs.pr-base || inputs.trigger-branch }}
        title: ${{ inputs.commit-message }}
        body: ${{ steps.compose_pr_body.outputs.body }}
        commit-message: ${{ inputs.commit-message }}
        delete-branch: true

    - name: Set outputs
      if: always()
      run: |
        echo "trigger-branch=${{ inputs.trigger-branch }}" >> $GITHUB_OUTPUT
        if [[ "${{ steps.commit_changes.outputs.commit-sha }}" != "" ]]; then
          echo "commit-sha=${{ steps.commit_changes.outputs.commit-sha }}" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ steps.create_pr.outputs.pull-request-url }}" != "" ]]; then
          echo "pr-url=${{ steps.create_pr.outputs.pull-request-url }}" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ steps.create_pr.outputs.pull-request-number }}" != "" ]]; then
          echo "pr-number=${{ steps.create_pr.outputs.pull-request-number }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
