name: "Poosh"
description: "Commit, push, or open a pull request for any changes in the repository. On push events, commits and pushes to a user-configurable branch (always prefixed with 'poosh/'). On other events, opens a pull request from that branch. Designed for use after your workflow has made changes."
icon: package
color: blue
inputs:
  commit-message:
    description: "Commit message to use when committing changes."
    required: true
  branch:
    description: "Suffix for the branch to push/PR to. The branch will always be 'poosh/{branch}'."
    required: true
  trigger-pr-number:
    description: "Optional: PR number of the triggering PR (e.g., 1234). If set, the PR body will include 'Triggered by #<number>'."
    required: false
    default: ""
  trigger-branch-name:
    description: "Optional: Name of the triggering branch (e.g., feature/my-feature). Used in PR body if trigger-pr-number is not set."
    required: false
    default: ""
outputs:
  branch:
    description: "The full branch name used for push/PR (always prefixed with 'poosh/')."
  commit-sha:
    description: "The commit SHA of the pushed commit (if a commit was made)."
  pr-url:
    description: "The URL of the created pull request (if a PR was opened)."
  pr-number:
    description: "The number of the created pull request (if a PR was opened)."
runs:
  using: "composite"
  steps:
    - name: Validate 'commit-message'
      run: |
        if [[ -z "${{ inputs.commit-message }}" || -z "$(echo "${{ inputs.commit-message }}" | xargs)" ]]; then
          echo "ERROR: 'commit-message' is required and must be a non-empty string."
          exit 1
        fi
      shell: bash

    - name: Validate 'branch'
      run: |
        if [[ -z "${{ inputs.branch }}" || -z "$(echo "${{ inputs.branch }}" | xargs)" ]]; then
          echo "ERROR: 'branch' is required and must be a non-empty string."
          exit 1
        fi
        if [[ "${{ inputs.branch }}" == *[!a-zA-Z0-9._/-]* ]]; then
          echo "ERROR: 'branch' contains invalid characters. Only alphanumeric, '.', '_', '-', and '/' are allowed."
          exit 1
        fi
      shell: bash

    - name: Validate triggers
      run: |
        if [[ -z "${{ inputs.trigger-pr-number }}" && -z "${{ inputs.trigger-branch-name }}" ]]; then
          echo "::warning::Neither 'trigger-pr-number' nor 'trigger-branch-name' was set. PR body will not include a trigger reference."
        fi
      shell: bash

    - name: Set poosh branch name
      id: poosh_branch
      run: |
        echo "branch=poosh/${{ inputs.branch }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check for changes
      id: check_changes
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Check if branch still exists on remote
      if: steps.check_changes.outputs.changed == 'true'
      id: branch_exists
      shell: bash
      run: |
        BRANCH_NAME="${{ steps.poosh_branch.outputs.branch }}"
        if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
          echo "branch_exists=true" >> $GITHUB_OUTPUT
        else
          echo "branch_exists=false" >> $GITHUB_OUTPUT
          echo "The branch $BRANCH_NAME no longer exists on GitHub. Exiting gracefully."
          exit 0
        fi

    - name: Commit and push changes (if possible)
      if: steps.check_changes.outputs.changed == 'true' && github.event_name == 'push' && steps.branch_exists.outputs.branch_exists == 'true'
      id: commit_push
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -B "${{ steps.poosh_branch.outputs.branch }}"
        git commit -m "${{ inputs.commit-message }}"
        git push origin "${{ steps.poosh_branch.outputs.branch }}"
        echo "commit-sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Pull Request
      if: steps.check_changes.outputs.changed == 'true' && github.event_name != 'push' && steps.branch_exists.outputs.branch_exists == 'true'
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        branch: ${{ steps.poosh_branch.outputs.branch }}
        base: ${{ github.head_ref || github.ref_name }}
        title: ${{ inputs.commit-message }}
        body: |
          This PR updates artifacts or files based on the latest workflow run. Generated by GitHub Actions.
          ${{ inputs.trigger-pr-number && format('Triggered by #{0}', inputs.trigger-pr-number) || (inputs.trigger-branch-name && format('Triggered by branch: {0}', inputs.trigger-branch-name) || '') }}
        commit-message: ${{ inputs.commit-message }}
        delete-branch: true

    - name: Set outputs
      if: always()
      run: |
        echo "branch=${{ steps.poosh_branch.outputs.branch }}" >> $GITHUB_OUTPUT
        if [[ "${{ steps.commit_push.outputs.commit-sha }}" != "" ]]; then
          echo "commit-sha=${{ steps.commit_push.outputs.commit-sha }}" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ steps.create_pr.outputs.pull-request-url }}" != "" ]]; then
          echo "pr-url=${{ steps.create_pr.outputs.pull-request-url }}" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ steps.create_pr.outputs.pull-request-number }}" != "" ]]; then
          echo "pr-number=${{ steps.create_pr.outputs.pull-request-number }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
