name: "Poosh"
description: "Attempts to push changes directly to the specified branch. If direct push is not possible (e.g., due to permissions or branch protection), creates a new branch and opens a pull request to the target branch instead."
icon: package
color: blue
inputs:
  commit-message:
    description: "Commit message to use when committing changes."
    required: true
  trigger-branch:
    description: "The branch where changes were made and where the action will attempt to push directly. If direct push fails, a PR will be opened to this branch."
    required: true
  pr-branch:
    description: "The name of the branch to create and push from if a PR is needed. If not provided, defaults to 'poosh/{trigger-branch}'. If provided and does not contain '/', it will be prefixed with 'poosh/'."
    required: false
    default: ""
  trigger-pr-number:
    description: "Optional: PR number of the triggering PR (e.g., 1234). If set, the PR body will include 'Triggered by #<number>'."
    required: false
    default: ""
outputs:
  trigger-branch:
    description: "The branch that was pushed to or targeted by the PR."
  commit-sha:
    description: "The commit SHA of the pushed commit (if a commit was made)."
  pr-url:
    description: "The URL of the created pull request (if a PR was opened)."
  pr-number:
    description: "The number of the created pull request (if a PR was opened)."
runs:
  using: "composite"
  steps:
    - name: Validate 'commit-message'
      run: |
        if [[ -z "${{ inputs.commit-message }}" || -z "$(echo "${{ inputs.commit-message }}" | xargs)" ]]; then
          echo "ERROR: 'commit-message' is required and must be a non-empty string."
          exit 1
        fi
      shell: bash

    - name: Validate 'trigger-branch'
      run: |
        if [[ -z "${{ inputs.trigger-branch }}" || -z "$(echo "${{ inputs.trigger-branch }}" | xargs)" ]]; then
          echo "ERROR: 'trigger-branch' is required and must be a non-empty string."
          exit 1
        fi
        if [[ "${{ inputs.trigger-branch }}" == *[!a-zA-Z0-9._/-]* ]]; then
          echo "ERROR: 'trigger-branch' contains invalid characters. Only alphanumeric, '.', '_', '-', and '/' are allowed."
          exit 1
        fi
      shell: bash

    - name: Validate 'pr-branch'
      run: |
        if [[ -n "${{ inputs.pr-branch }}" && "${{ inputs.pr-branch }}" == *[!a-zA-Z0-9._/-]* ]]; then
          echo "ERROR: 'pr-branch' contains invalid characters. Only alphanumeric, '.', '_', '-', and '/' are allowed."
          exit 1
        fi
      shell: bash

    - name: Validate triggers
      run: |
        if [[ -z "${{ inputs.trigger-pr-number }}" ]]; then
          echo "::warning::'trigger-pr-number' was not set. PR body will not include a trigger reference."
        fi
      shell: bash

    - name: Check for changes
      id: check_changes
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Commit changes
      if: steps.check_changes.outputs.changed == 'true'
      id: commit_changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "${{ inputs.commit-message }}"
      shell: bash

    - name: Try direct push to trigger branch
      if: steps.check_changes.outputs.changed == 'true'
      id: try_push
      run: |
        set -e
        git checkout "${{ inputs.trigger-branch }}"
        git pull origin "${{ inputs.trigger-branch }}" || true
        git push origin "${{ inputs.trigger-branch }}" && echo "push_success=true" >> $GITHUB_OUTPUT || echo "push_success=false" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create PR branch and push (if direct push failed)
      if: steps.check_changes.outputs.changed == 'true' && steps.try_push.outputs.push_success == 'false'
      id: pr_branch
      run: |
        set -e
        if [[ -z "${{ inputs.pr-branch }}" ]]; then
          PR_BRANCH="poosh/${{ inputs.trigger-branch }}"
        elif [[ "${{ inputs.pr-branch }}" != */* ]]; then
          PR_BRANCH="poosh/${{ inputs.pr-branch }}"
        else
          PR_BRANCH="${{ inputs.pr-branch }}"
        fi
        git checkout -b "$PR_BRANCH"
        git push origin "$PR_BRANCH"
        echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create Pull Request (if direct push failed)
      if: steps.check_changes.outputs.changed == 'true' && steps.try_push.outputs.push_success == 'false'
      id: create_pr
      uses: peter-evans/create-pull-request@v7
      with:
        branch: ${{ steps.pr_branch.outputs.pr_branch }}
        base: ${{ inputs.trigger-branch }}
        title: ${{ inputs.commit-message }}
        body: |
          This PR updates artifacts or files based on the latest workflow run. Generated by GitHub Actions.
          Triggered by branch: ${{ inputs.trigger-branch }}
          ${{ inputs.trigger-pr-number && format('Triggered by PR #{0}', inputs.trigger-pr-number) }}
        commit-message: ${{ inputs.commit-message }}
        delete-branch: true

    - name: Set outputs
      if: always()
      run: |
        echo "trigger-branch=${{ inputs.trigger-branch }}" >> $GITHUB_OUTPUT
        if [[ "${{ steps.commit_changes.outputs.commit-sha }}" != "" ]]; then
          echo "commit-sha=${{ steps.commit_changes.outputs.commit-sha }}" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ steps.create_pr.outputs.pull-request-url }}" != "" ]]; then
          echo "pr-url=${{ steps.create_pr.outputs.pull-request-url }}" >> $GITHUB_OUTPUT
        fi
        if [[ "${{ steps.create_pr.outputs.pull-request-number }}" != "" ]]; then
          echo "pr-number=${{ steps.create_pr.outputs.pull-request-number }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
