const fs = require('fs');
const path = require('path');

const DEFAULT_PR_BODY =
  'This PR was generated by [Poosh](https://github.com/BobTheBuidler/poosh) as part of a GitHub Actions workflow';
const REPO_SLUG = process.env.GITHUB_REPOSITORY || 'local/poosh';
const ACTION_FILE = path.resolve(__dirname, '..', '..', '..', '..', 'action.yml');
const ACTION_YAML = fs.readFileSync(ACTION_FILE, 'utf8');
const WORKFLOW_ERROR_REGEX =
  /create or update workflow|workflows? permission|workflows? scope/i;
const BRANCH_COLLISION_REGEX =
  /non-fast-forward|failed to push some refs|fetch first|updates were rejected/i;

module.exports = {
  DEFAULT_PR_BODY,
  REPO_SLUG,
  ACTION_FILE,
  ACTION_YAML,
  WORKFLOW_ERROR_REGEX,
  BRANCH_COLLISION_REGEX,
};
